<a href="https://colab.research.google.com/github/2303A52247/PNS/blob/main/PNS_Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr=np.array([1,2,34,6,32,14,65,7])
print(arr)
print(arr[0])
print(arr[2])

[ 1  2 34  6 32 14 65  7]
1
34


In [2]:
aa=[[1,2,3,4],[4,2,3,6]]
A=np.array([[1,2,3,4],[4,2,3,6]])
print(A)
print(type(A))
print(type(arr))

[[1 2 3 4]
 [4 2 3 6]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [3]:
np.ndim(arr)
np.ndim(A)
print(np.size(arr))
print(np.size(A))
print(np.shape(arr))

8
8
(8,)


In [4]:
print(np.shape(A))
A=np.array([[1,2,3],[3,4,5],[4,5,6]])
print(A)
print(A[0,:])
print(A[1,:])
print(A[2,:])
print(A[:,0])
print(A[:,1])
print(A[:,2])
print(A[2,1])

(2, 4)
[[1 2 3]
 [3 4 5]
 [4 5 6]]
[1 2 3]
[3 4 5]
[4 5 6]
[1 3 4]
[2 4 5]
[3 5 6]
5


In [5]:
import pandas as pd
Dataset={
"State": ['Andhra Pradesh', 'Maharashtra', 'Karnataka', 'Kerala', 'Tamil Nadu'],
"Capital": ['Hyderabad', 'Mumbai', 'Bengaluru', 'Trivandrum', 'Chennai'],
"Literacy %": [89, 77, 82, 97,85],
"Avg High Temp(c)": [33, 30, 29, 31, 32 ]}
df = pd.DataFrame(Dataset)
print(df)
print(df.sort_values('Literacy %', ascending=False))
print(df[['Capital']])
print(df[['State', 'Capital']])
print(df.loc[2])
print(df.iloc[1,2])
print(df.loc[1,'Literacy %'])
a={"Distance":[15, 13, 16, 16, 15, 16, 17, 14, 15, 16, 16,17, 14, 17, 17, 16, 14, 15, 16, 17, 14, 16, 15, 17, 1]}
df=pd.DataFrame(a)
print(df)
print('The number of elements in the column is =',df['Distance'].size)

            State     Capital  Literacy %  Avg High Temp(c)
0  Andhra Pradesh   Hyderabad          89                33
1     Maharashtra      Mumbai          77                30
2       Karnataka   Bengaluru          82                29
3          Kerala  Trivandrum          97                31
4      Tamil Nadu     Chennai          85                32
            State     Capital  Literacy %  Avg High Temp(c)
3          Kerala  Trivandrum          97                31
0  Andhra Pradesh   Hyderabad          89                33
4      Tamil Nadu     Chennai          85                32
2       Karnataka   Bengaluru          82                29
1     Maharashtra      Mumbai          77                30
      Capital
0   Hyderabad
1      Mumbai
2   Bengaluru
3  Trivandrum
4     Chennai
            State     Capital
0  Andhra Pradesh   Hyderabad
1     Maharashtra      Mumbai
2       Karnataka   Bengaluru
3          Kerala  Trivandrum
4      Tamil Nadu     Chennai
State           